spring:
  application:
    name:core
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: public
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${CORE_DB_URL:jdbc:postgresql://localhost:5432/core}
    username: myuser
    password: mypassword
    hikari:
      data-source-properties:
        stringtype: unspecified
  jpa:
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 50
server:
  port: ${CORE_PORT:5000}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
